FROM python:3.7-slim

RUN apt-get update && \
    apt-get install -y \
    curl && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl